services:
  # Service Backend Python
  - type: web
    name: dma-keynotes-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dma-keynotes-db
          property: connectionString
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: NOM_BD
        value: DMAKeynotesManager
      - key: PREFIX_API
        value: /api/v1

  # Service PostgreSQL
  - type: postgres
    name: dma-keynotes-db
    plan: free
    ipAllowList: []
    databaseName: DMAKeynotesManager
    postgresMajorVersion: 15